#!/bin/bash

CLOUDLET_HOST=$1
CLOUDLET_USER=$2
CLOUDLET_PASSWD=$3
REMOTE_PATH=$4

scp -R ./certs/ $CLOUDLET_USER:$CLOUDLET_PASSWD@$CLOUDLET_HOST:REMOTE_PATH
scp deploy_certs.sh $CLOUDLET_USER:$CLOUDLET_PASSWD@$CLOUDLET_HOST:/REMOTE_PATH
