#!/bin/sh
PYCLOUD_ENV="/usr/share/python/python-pycloud/lib/python2.7/site-packages/"

#Get the standard site-packages
SITE_PACKAGES=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`

#Link libvirt to our local virtualenv
echo "Linking libvirt to pycloud virtualenv"
VIRT="$SITE_PACKAGES/libvirt*"
ln -s -v $VIRT -t $PYCLOUD_ENV
echo "Done linking lib"

# Create data folder.
echo "Creating /var/pycloud"
mkdir -p /var/pycloud
echo "Creating data subfolder"
mkdir -p /var/pycloud/data

# Copying vm template to data folder.
PYCLOUD_HOME="/usr/share/python/python-pycloud/lib/python2.7/site-packages/pycloud-0.1.dev-py2.7.egg"
echo "Copying vm template to data folder"
cp $PYCLOUD_HOME/pycloud/pycloud/vm/vm_template.xml /var/pycloud/data/

# Change permission on /var/pycloud so all users can access it.
echo "Changing /var/pycloud permissions"
chmod -R 777 /var/pycloud

# Setup to ensure USB rules will work.
chmod a+r /etc/udev/rules.d/95-android.rules
udevadm control --reload-rules
service udev restart
udevadm trigger

# Set up freeradius permissions.
chown -R freerad:freerad /etc/freeradius/
chmod -R g+rw /etc/freeradius/
