#!/bin/sh

# Global vars.
CLOUDLET_USER="pycloud"
INSTALL_FOLDER="/var/pycloud"
DATA_FOLDER="${INSTALL_FOLDER}/data"

######################################
# User and folder setup.
######################################

# Create a user and group.
useradd -U -p ${CLOUDLET_USER} ${CLOUDLET_USER}
chown -R ${CLOUDLET_USER}:${CLOUDLET_USER} ${INSTALL_FOLDER}
chmod g+s ${INSTALL_FOLDER}

# Setup data folder.
mkdir -p ${DATA_FOLDER}

# Change permission on so all users can access it.
echo "Changing ${INSTALL_FOLDER} permissions"
chmod -R 777 ${INSTALL_FOLDER}

######################################
# Python libvirt setup
######################################

# Link libvirt to our local virtualenv
echo "Linking libvirt to pycloud virtualenv"
PYCLOUD_ENV="/usr/share/python/python-pycloud/lib/python2.7/site-packages/"
SITE_PACKAGES=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
VIRT="$SITE_PACKAGES/libvirt*"
ln -s -v $VIRT -t $PYCLOUD_ENV
echo "Done linking lib"

######################################
# Individual setup scripts.
######################################

# Execute setup scripts.
cd "${INSTALL_FOLDER}/scripts"

# Setup libvirtd and qemu.
bash qemu_setup.sh ${CLOUDLET_USER}

# Set up FreeRADIUS.
bash freerad_setup.sh ${CLOUDLET_USER}

# Setup USB.
bash libusb_setup.sh ${CLOUDLET_USER}

# Set up DNS server.
bash dns_setup.sh ${DATA_FOLDER}
